[package]
name = "openscad-language-server"
version = "0.1.0"
authors = ["dzhu"]
edition = "2018"
description = "A Language Server Protocol server for OpenSCAD"
readme = "out/README.md"
repository = "https://github.com/dzhu/openscad-language-server"
license = "MIT OR Apache-2.0"
keywords = ["language-server", "lsp"]
categories = ["development-tools"]
include = ["/src", "out/README.md"]

[dependencies]
home = "0.5.3"
lsp-server = "0.5.2"
lsp-types = "0.89.2"
serde = "1.0"
serde_json = "1.0"
tree-sitter = "0.20"
tree-sitter-openscad = "0.2.0"
