[package]
name = "openscad-language-server"
version = "0.1.0"
edition = "2018"

[dependencies]
lsp-server = "0.5.2"
lsp-types = "0.89.2"
serde = "1.0"
serde_json = "1.0"
tree-sitter = "0.20"
tree-sitter-openscad = "0.2.0"
